import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import "../../globals.css";
import { ThemeToggle } from "@/components/ui/theme-toggle";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BusinessLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 sticky top-0 items-center justify-between gap-2">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 h-4" />
          </div>
          <div className="flex items-center gap-4 px-4">
            <ThemeToggle />
          </div>
        </header>
        <main lang="en">
          <div className={`antialiased  h-full`}>
            {children}
          </div>
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
